import { useQuery } from "@tanstack/react-query";
import { useRouter } from "next/router";
import React from "react";
import { getCryptoDetails } from "../../Services/getDetails";
import Head from "next/head";
import Header from "../header";

const Index = () => {
  const router = useRouter();
  const coinId = router.query.slug;

  const { data, error, isLoading, isFetching } = useQuery({
    queryKey: ["cryptoDetail"],
    queryFn: () => getCryptoDetails(Number(coinId)),
  });

  const backToMain = () => {
    router.push("/");
  };

  return (
    <div>
      <Head>
        {!isFetching && <title>{data[0]?.name}</title>}

        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
      </Head>
      <Header />
      <h1>Detail Page for {coinId} </h1>
      <button type="button" onClick={backToMain}>
        {" "}
        Back to main
      </button>
      {isFetching ? (
        <p className="my-4">loading</p>
      ) : (
        <div className="my-4">{data[0]?.name}</div>
      )}
    </div>
  );
};

export default Index;
