import { ConnectButton, WalletButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useQuery } from "@tanstack/react-query";
import { getCryptoInfo } from "../Services/getCoins";

const Home: NextPage = () => {
  const router = useRouter();

  const { data, error, isLoading } = useQuery({
    queryKey: ["cryptos"],
    queryFn: getCryptoInfo,
  });

  if (isLoading) {
    return <p>Loading...</p>;
  }

  if (error) {
    return <p>Error: {error.message}</p>;
  }

  const goToDetails = () => {
    router.push("/coin-details");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        {/* <link href="/favicon.ico" rel="icon" /> */}
      </Head>

      <main className={styles.main}>
        <ConnectButton label="Connect Wallets" />
        <WalletButton wallet="metamask" />
        <button type="button" onClick={goToDetails}>
          {" "}
          go to details
        </button>
        <ul>
          {data.map((crypto: { id: number; name: string; symbol: string }) => (
            <div key={crypto.id}>
              <div onClick={() => console.log(crypto.id)}>{crypto.name}</div>
              <p>({crypto.symbol})</p>
            </div>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
