import { ConnectButton, WalletButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useQuery } from "@tanstack/react-query";
import { getCryptoList } from "../Services/getCoins";

const Home: NextPage = () => {
  const router = useRouter();
  const { data, error, isLoading } = useQuery({
    queryKey: ["cryptos"],
    queryFn: getCryptoList,
  });

  if (isLoading) {
    return null;
  }

  if (error) {
    return <p>Error: {error.message}</p>;
  }

  const goToDetails = (coinId: number) => {
    router.push({
      pathname: "/coin-details/[coinId]/",
      query: { coinId },
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
      </Head>

      <main className={styles.main}>
        <ConnectButton label="Connect Wallets" />
        <WalletButton wallet="metamask" />

        <ul>
          {data.map((crypto: { id: number; name: string; symbol: string }) => (
            <div
              key={crypto.id}
              className="flex  cursor-pointer"
              onClick={() => goToDetails(crypto.id)}>
              <div>{crypto.name}</div>
              <p>({crypto.symbol})</p>
            </div>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
