import { useQuery } from "@tanstack/react-query";
import { useRouter } from "next/router";
import React from "react";
import { getCryptoDetails } from "../../../services/getDetails";
import Head from "next/head";
import Header from "../../../components/header";
import Image from "next/image";

const Index = () => {
  const router = useRouter();
  const coinId = router.query.slug;

  const { data, error, isLoading, isFetching } = useQuery({
    queryKey: ["cryptoDetail"],
    queryFn: () => getCryptoDetails(Number(coinId)),
  });

  const backToMain = () => {
    router.push("/");
  };
  const coinName = () => {
    if (!isFetching) {
      return data[0]?.name;
    }
  };
  const imageSrc = `https://www.coinlore.com/img/50x50/ethereum.png`;

  return (
    <div>
      <Head>
        {!isFetching && <title>{data[0]?.name}</title>}

        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
      </Head>

      <h1>Detail Page for {coinId} </h1>
      <button type="button" onClick={backToMain}>
        {" "}
        Back to main
      </button>
      <Image width={50} height={50} src={imageSrc} alt="crypto-image" />
      {isFetching ? (
        <p className="my-4">loading</p>
      ) : (
        <div className="my-4">{coinName()}</div>
      )}
    </div>
  );
};

export default Index;
